---
# tasks file for docker

- name: "Устанавливаем необходимые пакеты для Docker"
  apt: name={{ item }} state=latest update_cache=yes
  loop: [ 'apt-transport-https', 'ca-certificates', 'curl', 'software-properties-common', 'python3-pip', 'virtualenv', 'python3-setuptools']

- name: "Добавляем Docker GPG apt Key"
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: "Добавляем Docker Repository"
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu bionic stable
    state: present

- name: "Обновляем apt и устанавливаем docker-ce"
  apt: update_cache=yes name=docker-ce state=latest

- name: "Устанавливаем Docker Module для Python"
  pip:
    name: docker