---
# Playbook with tasks fo dev

- hosts: dev
  vars_files:
    # Подключаем файлы с переменными
    - ./vars/dev_users.secret
    - ./vars/ssh_params.yml
  become: yes
  roles:
#    - create-users
#    - sshd-config
#    - install-packages
    - redis
#    - ufw
