---
# Playbook with tasks for check-ip

- hosts: dev
  tasks:
    - name: "Получаем из ansible_host ip->interface"
      get_ip_facts: ip={{ hostvars[inventory_hostname]['ansible_host'] }}
      register: ip_facts
    - name: "Выводим приватный и публичный адреса"
      debug:
        msg: 
          - 'Приватный IP: {{ ip_facts.network_priv }}, на интерфейсе: {{ ip_facts.ifname_priv }}'
          - 'Публичный IP: {{ ip_facts.network_pub }}, на интерфейсе: {{ ip_facts.ifname_pub }}'