---
# Playbook with tasks for dev

- hosts: dev
  # Подключаем файлы с переменными
  vars_files:
    - ./vars/dev_users.secret
    - ./vars/ssh_params.yml
    - ./vars/redis_params.yml
  # Даём рут права
  become: yes
  # Решил все разнести по ролям, так удобнее читать =)
  # Что не нужно просто закомментить
  roles:
    - install-packages
    - docker-install
    - check-ip
    - docker-redis
    - create-users
    - sshd-config
    # - redis
    # - ufw
