---
# tasks file for check-ip

- name: "Смотрим не совпадение ansible_all_ipv4_addresses с ansible_host"
  set_fact: private_ip={{ item }}
  loop: "{{ ansible_all_ipv4_addresses }}"
  when: item != ansible_host

- name: "Что не совпало то и есть - серый интерфейс"
  debug:
    msg: "{{ private_ip }}"
