---
# tasks file for iptables

- name: "Iptables - разрешаем ssh на сером ip"
  iptables:
      chain: INPUT
      protocol: tcp
      destination: '{{ private_ip }}'
      destination_port: '{{ ssh_port }}'
      jump: ACCEPT

- name: "Iptables - разрешаем tcp/{{ redis_port }} на сером ip"
  iptables:
    chain: INPUT
    protocol: tcp
    destination: '{{ private_ip }}'
    destination_port: '{{ redis_port }}'
    jump: ACCEPT

- name: "Iptables - разрешаем ICMP на белом ip"
  iptables:
      chain: INPUT
      protocol: icmp
      destination: '{{ ansible_host }}'
      jump: ACCEPT

- name: "Iptables - запрещаем входящий на ветке INPUT"
  iptables:
    chain: INPUT
    jump: DROP
